name: daily_needs
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^1.0.1
  cupertino_icons: ^1.0.3
  firebase_crashlytics: ^0.4.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.4.4
  http: ^0.12.0+4
  toast: ^0.1.5
  chips_choice: ^2.0.1
  firebase_auth: 
  #google_sign_in: ^4.5.1
  geocoder: ^0.2.1
  geolocator: 
  shared_preferences:
  language_pickers: ^0.2.0+1
  webview_flutter:
  url_launcher: ^6.0.5
  firebase_messaging: ^8.0.0-dev.15
  # firebase_auth: any
  firebase_core:
  firebase_database: ^6.0.0
  flutter_webview_plugin: ^0.4.0
  flutter_local_notifications:
  rxdart:
  google_maps_flutter: ^0.5.28+1
  flutter_twilio_voice: ^0.0.3
  cached_network_image: ^2.2.0+1
  # permission: ^0.1.7
  autocomplete_textfield: ^1.7.3
  flappy_search_bar: ^1.7.2
  google_map_polyline:
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  location: ^3.0.2
  #flutter_launcher_icons: ^0.7.5
  android_intent: any
  agora_rtc_engine: ^4.0.6
  permission_handler: ^5.0.1
  fluttertoast: any
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  image_path: "images/playstore-icon.png" 
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that images/car_worker.pngyou can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/fb.png
     - images/newgoogle.png
     - images/Instagram.png
     - images/facebook.png
     - images/Twitter.png
     - images/india.png
     - images/car_worker.png
     - images/flight.png
     - images/no_category.png
     - images/service_image1.png
     - images/service_image2.png
     - images/service_image3.png
     - images/service_image4.png
     - images/service_image5.png
     - images/map_bike.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: VAG
      fonts:
        - asset: font/VAG Rounded Bold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

